lib/pow_demo_web/router.ex
defmodule PowDemoWeb.Router do
  use PowDemoWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword, PowEmailConfirmation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end


  scope "/" do
    pipe_through :browser

    get "/", PowDemoWeb.PageController, :index

    pow_routes()
    pow_extension_routes()
  end

  scope "/", PowDemoWeb do
    pipe_through [:browser, :protected]

    get "/secure", SecureController, :index

    # Add your protected routes here
  end

  # Other scopes may use custom stacks.
  # scope "/api", PowDemoWeb do
  #   pipe_through :api
  # end
end

lib/pow_demo/application.ex
defmodule PowDemo.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      PowDemo.Repo,
      # Start the endpoint when the application starts
      PowDemoWeb.Endpoint
      # Starts a worker by calling: PowDemo.Worker.start_link(arg)
      # {PowDemo.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: PowDemo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    PowDemoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/pow_demo/repo.ex
defmodule PowDemo.Repo do
  use Ecto.Repo,
    otp_app: :pow_demo,
    adapter: Ecto.Adapters.Postgres
end

lib/pow_demo/users/user.ex
defmodule PowDemo.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowEmailConfirmation]

  schema "users" do
    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
  end
end

lib/pow_demo_web/controllers/page_controller.ex
defmodule PowDemoWeb.PageController do
  use PowDemoWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/pow_demo_web/controllers/secure_controller.ex
defmodule PowDemoWeb.SecureController do
  use PowDemoWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/pow_demo_web/views/error_view.ex
defmodule PowDemoWeb.ErrorView do
  use PowDemoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/pow_demo_web/views/layout_view.ex
defmodule PowDemoWeb.LayoutView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/views/page_view.ex
defmodule PowDemoWeb.PageView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/views/pow/registration_view.ex
defmodule PowDemoWeb.Pow.RegistrationView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/views/pow/session_view.ex
defmodule PowDemoWeb.Pow.SessionView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/views/pow_email_confirmation/mailer_view.ex
defmodule PowDemoWeb.PowEmailConfirmation.MailerView do
  use PowDemoWeb, :mailer_view

  def subject(:email_confirmation, _assigns), do: "Confirm your email address"
end

lib/pow_demo_web/views/pow_reset_password/mailer_view.ex
defmodule PowDemoWeb.PowResetPassword.MailerView do
  use PowDemoWeb, :mailer_view

  def subject(:reset_password, _assigns), do: "Reset password link"
end

lib/pow_demo_web/views/pow_reset_password/reset_password_view.ex
defmodule PowDemoWeb.PowResetPassword.ResetPasswordView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/views/secure_view.ex
defmodule PowDemoWeb.SecureView do
  use PowDemoWeb, :view
end

lib/pow_demo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "PowDemo · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul class="row">
            <%= if Pow.Plug.current_user(@conn) do %>
              <li class="column"><%= link "Logout", to: Routes.pow_session_path(@conn, :delete), method: :delete%></li>
              <li class="column"><%= link "Super Secret", to: Routes.secure_path(@conn, :index)%></li>
              <li class="column"><%= link "Edit", to: Routes.pow_registration_path(@conn, :edit)%></li>
            <% else %>
              <li class="column"><%= link "Login", to: Routes.pow_session_path(@conn, :new)%></li>
              <li class="column"><%= link "Registration", to: Routes.pow_registration_path(@conn, :new)%></li>
            <% end %>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img src='<%= Routes.static_path(@conn, "/images/pow.svg") %>' height="50px" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/pow_demo_web/templates/page/index.html.eex
<div id="home-page">
  <section class="phx-hero">
    <h1>Welcome to Evan's Pow Demo</h1>
    <p>A robust, modular and extendable<div class="">user management solution.</div></p>
  </section>

  <section class="row">

  </section>
</div>

lib/pow_demo_web/templates/pow/session/new.html.eex
<h1>Sign in</h1>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>

  <%= label f, :password %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>
  <span><%= link("Reset password", to: Routes.pow_reset_password_reset_password_path(@conn, :new)) %></span>

  <div>
    <%= submit "Sign in" %>
  </div>
<% end %>


<span><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></span>

lib/pow_demo_web/templates/pow_reset_password/reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation %>
  <%= password_input f, :password_confirmation %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>


<span><%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %></span>

lib/pow_demo_web/templates/pow_reset_password/reset_password/new.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

lib/pow_demo_web/templates/secure/index.html.eex
<div id="secure-page">
  <section class="phx-hero">
    <h1>Wow super safe!</h1>
    <p>A page only the cool people can see!</p>
  </section>
</div>